<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resource\icon_256x256.ico</ApplicationIcon>
    <StartupObject>YXSTool.View.App</StartupObject>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsPublishable>True</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <Page Remove="View\App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Include="View\App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resource\icon_256x256.ico">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="iNKORE.UI.WPF.Modern" Version="0.10.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\YXSFocTool\YXSFocTool.csproj" />
  </ItemGroup>

</Project>
